version: 1.0.{build}

image: ubuntu1804

build: off

init:
    git config --global core.autocrlf input

install:
    sudo apt-add-repository ppa:ubuntu-toolchain-r/test

    sudo apt-get -y update

    sudo update-alternatives --set gcc /usr/bin/gcc-8

    sudo update-alternatives --set g++ /usr/bin/g++-8

    sudo apt-get -y install libhdf5-openmpi-dev

    cd Zeta/Setup

    . setup.sh

    cd $APPVEYOR_BUILD_FOLDER

    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/Zeta/Setup/mshtocgns-7.0.0/Zeta/Libraries/boost-1.74.0/release/lib
    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/Zeta/Setup/mshtocgns-7.0.0/Zeta/Libraries/cgns-4.1.2/release/lib
    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/Zeta/Libraries/mshtocgns-7.0.0/release/lib
    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/Zeta/Libraries/metis-5.1.0/release/lib

    export LD_LIBRARY_PATH

    mkdir build

    cd build

    cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=TRUE

    make -j 2

    cd bin

    mpirun -np 2 ./DomainDividerTest

    mpirun -np 2 ./MetisInterfaceTest

    mpirun -np 2 ./ParallelCgnsInterfaceTest

    cd ..

    make test
